version: "3.8"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: php-oop-app
    restart: always
    working_dir: /var/www/
    volumes:
      - ../:/var/www

  nginx:
    image: nginx:1.19-alpine
    container_name: php-oop-server
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ../:/var/www
      - ./nginx:/etc/nginx/conf.d

  db:
    container_name: php-oop-database
    image: mysql:8.0
    volumes:
      - ./storage/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
